"""
Foundry ↔ TinyTroupe adapter (Sprint 1D).

Architectural rules (enforced by scripts/check-import-boundaries.mjs):
  * `tinytroupe` may ONLY be imported inside this package.
  * Provider SDKs (openai, anthropic, …) may NEVER be imported here directly —
    TinyTroupe brings its own OpenAI integration that reads `OPENAI_API_KEY`
    (or `AZURE_OPENAI_*`) from the subprocess environment. The TypeScript host
    is responsible for placing the decrypted BYOK secret in that environment
    for the duration of the subprocess only.

The runtime degrades gracefully when `tinytroupe` is not importable so the
package can be installed and typechecked in CI without the heavy dependency.
"""

from __future__ import annotations

from typing import Any


def _tinytroupe_available() -> bool:
    try:
        import tinytroupe  # type: ignore[import-not-found]  # noqa: F401
        return True
    except Exception:  # pragma: no cover - import-time check
        return False


class TinyTroupeAdapterStub:
    """Sprint 0-style stub kept for backwards compatibility with import sites."""

    async def generate_personas(self, *args: Any, **kwargs: Any) -> Any:
        raise NotImplementedError("Use TinyTroupeRuntime.generate_personas via the CLI bridge.")


class TinyTroupeRuntime:
    """
    Thin synchronous wrapper used by `cli.py`.

    Methods accept already-validated dicts (brief + args) and return
    JSON-serialisable dicts that match the contract types declared in
    `@foundry/contracts` (PersonaLab*).
    """

    def __init__(self) -> None:
        if not _tinytroupe_available():
            raise NotImplementedError(
                "tinytroupe is not importable; install it in the subprocess's "
                "Python environment to use the TinyTroupe engine, or omit "
                "VENTUREOS_TINYTROUPE_PYTHON to use the built-in engine."
            )
        from tinytroupe.agent import TinyPerson  # type: ignore[import-not-found]
        from tinytroupe.environment import TinyWorld  # type: ignore[import-not-found]
        from tinytroupe.factory import TinyPersonFactory  # type: ignore[import-not-found]

        self._TinyPerson = TinyPerson
        self._TinyWorld = TinyWorld
        self._TinyPersonFactory = TinyPersonFactory

    # ------------------------------------------------------------------

    def generate_personas(self, brief: dict[str, Any], args: dict[str, Any]) -> dict[str, Any]:
        n = max(1, min(12, int(args.get("n", 6))))
        prompt = (
            f"Business idea: {brief.get('businessIdea', '')}. "
            f"Target market: {brief.get('targetMarket', '')}. "
            f"Customer type: {brief.get('customerType', '')}. "
            f"Region: {brief.get('region', '')}. "
            f"Business size: {brief.get('businessSize', '')}."
        )
        factory = self._TinyPersonFactory(prompt)
        agents = factory.generate_people(n)
        personas: list[dict[str, Any]] = []
        for i, agent in enumerate(agents, start=1):
            spec = agent.minibio() if hasattr(agent, "minibio") else str(agent)
            getter = getattr(agent, "get", None)
            def _g(key: str, default: Any) -> Any:
                return getter(key, default) if callable(getter) else default
            personas.append({
                "id": f"p{i}",
                "name": getattr(agent, "name", f"Persona {i}"),
                "role": _g("occupation", "Stakeholder"),
                "businessContext": spec,
                "goals": _g("goals", []),
                "painPoints": _g("pain_points", []),
                "motivations": _g("motivations", []),
                "objections": _g("objections", []),
                "buyingTriggers": _g("buying_triggers", []),
                "decisionPower": _g("decision_power", "medium"),
                "quote": _g("quote", ""),
                "confidenceScore": 0.7,
                "evidenceNotes": [f"Generated by TinyTroupe from prompt: {prompt[:120]}"],
            })
        return {"personas": personas}

    def run_interview(self, brief: dict[str, Any], args: dict[str, Any]) -> dict[str, Any]:
        persona = args.get("persona", {})
        topic = args.get("topic", "discovery")
        questions: list[str] = args.get("questions", [])
        agent = self._make_person(persona, brief)
        turns: list[dict[str, str]] = []
        for q in questions:
            turns.append({"speaker": "interviewer", "content": q})
            agent.listen(q)
            agent.act()
            reply = self._last_utterance(agent) or "(no reply)"
            turns.append({"speaker": "persona", "content": reply})
        return {
            "personaId": persona.get("id", ""),
            "topic": topic,
            "turns": turns,
            "summary": f"TinyTroupe interview with {persona.get('name', 'persona')} on {topic}.",
        }

    def run_focus_group(self, brief: dict[str, Any], args: dict[str, Any]) -> dict[str, Any]:
        personas: list[dict[str, Any]] = args.get("personas", [])
        topic = args.get("topic", "discovery")
        rounds = max(1, min(5, int(args.get("rounds", 3))))
        agents = [self._make_person(p, brief) for p in personas]
        world = self._TinyWorld("PersonaLab Focus Group", agents)
        world.broadcast(f"Focus group topic: {topic}")
        world.run(rounds)
        turns = self._collect_turns(agents)
        return {
            "topic": topic,
            "participantIds": [p["id"] for p in personas],
            "turns": turns,
            "summary": f"TinyTroupe focus group of {len(agents)} participants over {rounds} rounds.",
            "agreements": [],
            "disagreements": [],
        }

    def run_buying_committee(self, brief: dict[str, Any], args: dict[str, Any]) -> dict[str, Any]:
        """
        Sprint 1D.5 — phased multi-agent deliberation.

        Runs the same four phases as the built-in engine (initial positions,
        challenges, responses, consensus) via `TinyWorld.broadcast` + `world.run(1)`.
        Each phase captures the new utterances each agent emits and converts
        them into the structured deliberation shape declared in
        `@foundry/contracts` (`BuyingCommitteeDeliberation`).

        The decision is derived from the FINAL consensus positions, not from
        keyword scoring over the whole transcript.
        """
        personas: list[dict[str, Any]] = args.get("personas", [])
        offer = args.get("offerSummary", "")
        agents = [self._make_person(p, brief) for p in personas]
        world = self._TinyWorld("PersonaLab Buying Committee", agents)

        # Snapshot per agent so we can capture only this phase's new utterances.
        cursors: dict[str, int] = {self._agent_key(a): self._utterance_count(a) for a in agents}

        def _phase(prompt: str) -> dict[str, list[str]]:
            world.broadcast(prompt)
            world.run(1)
            new_by_agent: dict[str, list[str]] = {}
            for agent in agents:
                key = self._agent_key(agent)
                all_utts = self._utterances_for(agent)
                cursor = cursors.get(key, 0)
                new_by_agent[key] = all_utts[cursor:]
                cursors[key] = len(all_utts)
            return new_by_agent

        # Phase 1 — initial positions
        p1 = _phase(
            f"BUYING COMMITTEE PHASE 1 — INITIAL POSITIONS. Offer under evaluation: {offer}. "
            "State your starting position out loud: choose ONE of 'support', "
            "'support_with_concerns', 'pilot_first', 'reject'. Then list your "
            "top concerns and how willing you are to adopt this offer."
        )
        initial_positions = [
            _to_opinion(p, p1.get(self._agent_key(a), []))
            for p, a in zip(personas, agents, strict=False)
        ]

        # Phase 2 — challenges
        p2 = _phase(
            "BUYING COMMITTEE PHASE 2 — CHALLENGES. Challenge another participant's "
            "position. Address them by name. Pick a specific topic: assumption, "
            "pricing, onboarding, roi, workflow, or trust."
        )
        challenges = _to_challenges(personas, agents, p2, self._agent_key)

        # Phase 3 — responses
        p3 = _phase(
            "BUYING COMMITTEE PHASE 3 — RESPONSES. Respond to the challenge raised "
            "against your position. You may defend your stance or change your mind. "
            "Say explicitly whether your position has changed."
        )
        responses = _to_responses(personas, agents, p3, self._agent_key, challenges)

        # Phase 4 — consensus
        p4 = _phase(
            "BUYING COMMITTEE PHASE 4 — CONSENSUS. State your FINAL position after "
            "this discussion: 'support', 'support_with_concerns', 'pilot_first', or 'reject'. "
            "Briefly explain whether you changed your mind and why."
        )
        consensus = [
            _to_opinion(p, p4.get(self._agent_key(a), []))
            for p, a in zip(personas, agents, strict=False)
        ]

        # Build deliberation summary fields.
        opinion_changes = _compute_opinion_changes(initial_positions, consensus)
        consensus_level = _derive_consensus_level(consensus)
        decision = _derive_decision_from_consensus(consensus)
        unresolved = _collect_unresolved_objections(consensus)

        deliberation: dict[str, Any] = {
            "phases": {
                "initialPositions": initial_positions,
                "challenges": challenges,
                "responses": responses,
                "consensus": consensus,
            },
            "opinionChanges": opinion_changes,
            "unresolvedObjections": unresolved,
            "strongestSupportingArguments": _strongest(consensus, supporting=True),
            "strongestOpposingArguments": _strongest(consensus, supporting=False),
            "whatWouldChangeMinds": [],
            "consensusLevel": consensus_level,
            "confidenceScore": 0.6 if consensus_level in ("strong", "moderate") else 0.4,
        }

        members = _derive_members(personas, initial_positions, consensus)
        return {
            "offerSummary": offer,
            "members": members,
            "decision": decision,
            "decisionRationale": (
                f"Consensus reached at level '{consensus_level}' after a 4-phase "
                f"agent deliberation. {len(opinion_changes)} participant(s) changed position."
            ),
            "nextSteps": [],
            "deliberation": deliberation,
        }

    # ------------------------------------------------------------------

    def _make_person(self, persona: dict[str, Any], _brief: dict[str, Any]) -> Any:
        agent = self._TinyPerson(persona.get("name", "Persona"))
        if hasattr(agent, "define"):
            agent.define("occupation", persona.get("role", "Stakeholder"))
            agent.define("context", persona.get("businessContext", ""))
        return agent

    def _last_utterance(self, agent: Any) -> str:
        history = getattr(agent, "episodic_memory", None)
        if history is None:
            return ""
        items = list(history) if hasattr(history, "__iter__") else []
        for item in reversed(items):
            content = item.get("content") if isinstance(item, dict) else None
            if isinstance(content, str) and content.strip():
                return content
        return ""

    def _collect_turns(self, agents: list[Any]) -> list[dict[str, str]]:
        out: list[dict[str, str]] = []
        for agent in agents:
            speaker_id = getattr(agent, "name", "?")
            history = getattr(agent, "episodic_memory", None) or []
            for item in history:
                content = item.get("content") if isinstance(item, dict) else None
                if isinstance(content, str) and content.strip():
                    out.append({"speakerPersonaId": speaker_id, "content": content})
        return out

    def _utterances_for(self, agent: Any) -> list[str]:
        history = getattr(agent, "episodic_memory", None) or []
        out: list[str] = []
        for item in history:
            if not isinstance(item, dict):
                continue
            # Skip messages broadcast by the world or addressed at the agent —
            # we want only what the agent itself produced.
            speaker = item.get("speaker")
            if speaker in ("world", "interviewer", "system", "moderator"):
                continue
            content = item.get("content")
            if isinstance(content, str) and content.strip():
                out.append(content)
        return out

    def _utterance_count(self, agent: Any) -> int:
        return len(self._utterances_for(agent))

    def _agent_key(self, agent: Any) -> str:
        return str(getattr(agent, "name", id(agent)))


# ── Stance heuristics ────────────────────────────────────────────────────────
# Deterministic keyword scan over the agent's utterances. Avoids a second LLM
# round-trip per committee member; good enough to drive the decision field.

_POSITIVE = ("love", "great", "excited", "buy", "purchase", "yes", "perfect", "sign", "want")
_NEGATIVE = ("hate", "no thanks", "won't", "concerned", "risk", "blocker", "expensive", "reject")
_OBJECTION_HINT = ("but ", "however", "concern", "worry", "afraid", "risk", "blocker")


def _infer_stance(text: str) -> str:
    if not text:
        return "neutral"
    lower = text.lower()
    pos = sum(lower.count(w) for w in _POSITIVE)
    neg = sum(lower.count(w) for w in _NEGATIVE)
    if pos >= 2 and pos > neg * 2:
        return "champion"
    if pos > neg:
        return "supporter"
    if neg > pos * 2:
        return "blocker"
    if neg > pos:
        return "skeptic"
    return "neutral"


def _extract_objections(utterances: list[str]) -> list[str]:
    out: list[str] = []
    for u in utterances:
        lower = u.lower()
        if any(hint in lower for hint in _OBJECTION_HINT):
            cleaned = u.strip().rstrip(".")
            if cleaned and cleaned not in out:
                out.append(cleaned[:200])
    return out[:5]


def _decide(stance_tally: dict[str, int]) -> str:
    blockers = stance_tally.get("blocker", 0)
    skeptics = stance_tally.get("skeptic", 0)
    supporters = stance_tally.get("supporter", 0) + stance_tally.get("champion", 0)
    if blockers >= 1 and supporters == 0:
        return "reject"
    if supporters > skeptics + blockers:
        return "buy"
    if supporters > 0:
        return "pilot"
    return "defer"


__all__ = [
    "TinyTroupeAdapterStub",
    "TinyTroupeRuntime",
    "_infer_stance",
    "_extract_objections",
    "_decide",
    "_infer_position",
    "_derive_consensus_level",
    "_derive_decision_from_consensus",
]

# ── Phased deliberation helpers (Sprint 1D.5) ───────────────────────────────

_POSITION_KEYWORDS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("reject",                ("reject", "no thanks", "won't", "will not", "blocker", "deal-breaker")),
    ("pilot_first",           ("pilot", "trial", "try first", "evaluate first", "30-day", "60-day", "90-day")),
    ("support_with_concerns", ("but ", "however", "concern", "worry", "afraid", "risk", "provided that")),
    ("support",               ("support", "love it", "great", "excited", "buy", "purchase", "yes", "sign", "perfect")),
)

_POSITION_TO_STANCE = {
    "support": "champion",
    "support_with_concerns": "supporter",
    "pilot_first": "neutral",
    "reject": "blocker",
}


def _infer_position(text: str) -> str:
    """Map a free-form utterance to one of the four committee positions."""
    if not text:
        return "support_with_concerns"
    lower = text.lower()
    # Walk in priority order: reject > pilot > support_with_concerns > support.
    for label, hints in _POSITION_KEYWORDS:
        if any(h in lower for h in hints):
            return label
    return "support_with_concerns"


def _to_opinion(persona: dict[str, Any], utterances: list[str]) -> dict[str, Any]:
    joined = " ".join(utterances).strip()
    position = _infer_position(joined)
    concerns = _extract_objections(utterances)
    enthusiasm = {
        "support": 0.9,
        "support_with_concerns": 0.6,
        "pilot_first": 0.5,
        "reject": 0.2,
    }[position]
    return {
        "personaId": persona.get("id", ""),
        "position": position,
        "enthusiasm": enthusiasm,
        "concerns": concerns,
        "willingnessToAdopt": joined[:160] if joined else "",
        "rationale": joined[:400] if joined else "TinyTroupe agent produced no utterance in this phase.",
    }


def _to_challenges(
    personas: list[dict[str, Any]],
    agents: list[Any],
    phase_utterances: dict[str, list[str]],
    agent_key: Any,
) -> list[dict[str, Any]]:
    ids = [p.get("id", "") for p in personas]
    names_lower = {agent_key(a).lower(): p.get("id", "") for p, a in zip(personas, agents, strict=False)}
    out: list[dict[str, Any]] = []
    for persona, agent in zip(personas, agents, strict=False):
        key = agent_key(agent)
        utts = phase_utterances.get(key, [])
        if not utts:
            continue
        # Address-detection: look for another participant's name in the utterance.
        joined = " ".join(utts)
        target_id = ""
        joined_lower = joined.lower()
        for name_lower, pid in names_lower.items():
            if pid == persona.get("id", ""):
                continue
            if name_lower and name_lower in joined_lower:
                target_id = pid
                break
        if not target_id:
            # Fall back to the first other participant.
            others = [pid for pid in ids if pid != persona.get("id", "")]
            target_id = others[0] if others else ""
        if not target_id:
            continue
        out.append({
            "fromPersonaId": persona.get("id", ""),
            "toPersonaId": target_id,
            "topic": _infer_topic(joined),
            "argument": joined.strip()[:400],
        })
    return out


_TOPIC_KEYWORDS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("pricing",    ("price", "cost", "expensive", "cheap", "budget", "fee")),
    ("onboarding", ("onboard", "setup", "install", "deploy", "training")),
    ("roi",        ("roi", "return", "value", "payback", "revenue", "growth")),
    ("workflow",   ("workflow", "click", "process", "step", "daily", "team")),
    ("trust",      ("trust", "security", "data", "privacy", "compliance")),
    ("assumption", ("assume", "assumption", "premise", "hypothesis")),
)


def _infer_topic(text: str) -> str:
    lower = text.lower()
    for label, hints in _TOPIC_KEYWORDS:
        if any(h in lower for h in hints):
            return label
    return "other"


def _to_responses(
    personas: list[dict[str, Any]],
    agents: list[Any],
    phase_utterances: dict[str, list[str]],
    agent_key: Any,
    challenges: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for persona, agent in zip(personas, agents, strict=False):
        key = agent_key(agent)
        utts = phase_utterances.get(key, [])
        if not utts:
            continue
        joined = " ".join(utts).strip()
        # Match this responder to the first challenge addressed AT them.
        idx = -1
        for i, c in enumerate(challenges):
            if c.get("toPersonaId") == persona.get("id", ""):
                idx = i
                break
        if idx < 0:
            continue
        lower = joined.lower()
        changed = any(p in lower for p in ("changed my mind", "you are right", "fair point", "i agree now", "i will pilot", "i'll pilot"))
        out.append({
            "fromPersonaId": persona.get("id", ""),
            "challengeIndex": idx,
            "argument": joined[:400],
            "changedOpinion": changed,
        })
    return out


def _compute_opinion_changes(
    initial: list[dict[str, Any]],
    consensus: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    initial_by_id = {o["personaId"]: o["position"] for o in initial}
    out: list[dict[str, Any]] = []
    for o in consensus:
        before = initial_by_id.get(o["personaId"])
        if before and before != o["position"]:
            out.append({
                "personaId": o["personaId"],
                "fromPosition": before,
                "toPosition": o["position"],
                "reason": "Position shifted during 4-phase deliberation.",
            })
    return out


def _derive_consensus_level(consensus: list[dict[str, Any]]) -> str:
    if not consensus:
        return "weak"
    positions = [o["position"] for o in consensus]
    unique = set(positions)
    if len(unique) == 1:
        return "strong"
    if len(unique) >= 3:
        return "split"
    # 2 unique positions
    top_count = max(positions.count(p) for p in unique)
    return "moderate" if top_count / len(consensus) >= 0.75 else "weak"


def _derive_decision_from_consensus(consensus: list[dict[str, Any]]) -> str:
    if not consensus:
        return "defer"
    counts = {"support": 0, "support_with_concerns": 0, "pilot_first": 0, "reject": 0}
    for o in consensus:
        pos = o.get("position", "support_with_concerns")
        if pos in counts:
            counts[pos] += 1
    if counts["reject"] > len(consensus) / 2:
        return "reject"
    if counts["support"] == len(consensus):
        return "buy"
    if counts["support"] + counts["support_with_concerns"] > len(consensus) / 2:
        return "pilot"
    return "defer"


def _collect_unresolved_objections(consensus: list[dict[str, Any]]) -> list[str]:
    out: list[str] = []
    for o in consensus:
        if o.get("position") in ("reject", "pilot_first"):
            for c in o.get("concerns", []):
                if c and c not in out:
                    out.append(c)
    return out[:8]


def _strongest(consensus: list[dict[str, Any]], *, supporting: bool) -> list[str]:
    out: list[str] = []
    for o in consensus:
        pos = o.get("position", "")
        if supporting and pos in ("support", "support_with_concerns"):
            r = o.get("rationale", "")
            if r:
                out.append(r[:200])
        elif not supporting and pos in ("reject", "pilot_first"):
            r = o.get("rationale", "")
            if r:
                out.append(r[:200])
    return out[:5]


def _derive_members(
    personas: list[dict[str, Any]],
    initial: list[dict[str, Any]],
    consensus: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    final_by_id = {o["personaId"]: o for o in consensus}
    initial_by_id = {o["personaId"]: o for o in initial}
    out: list[dict[str, Any]] = []
    for p in personas:
        pid = p.get("id", "")
        opinion = final_by_id.get(pid) or initial_by_id.get(pid)
        if not opinion:
            out.append({
                "personaId": pid,
                "committeeRole": p.get("role", "Participant"),
                "stance": "neutral",
                "rationale": "",
                "blockingObjections": [],
            })
            continue
        position = opinion.get("position", "support_with_concerns")
        stance = _POSITION_TO_STANCE.get(position, "neutral")
        # Refine by enthusiasm.
        enth = float(opinion.get("enthusiasm", 0.5))
        if stance == "champion" and enth < 0.7:
            stance = "supporter"
        if stance == "blocker" and enth > 0.3:
            stance = "skeptic"
        objections = list(opinion.get("concerns", [])) if position in ("reject", "pilot_first") else []
        out.append({
            "personaId": pid,
            "committeeRole": p.get("role", "Participant"),
            "stance": stance,
            "rationale": opinion.get("rationale", ""),
            "blockingObjections": objections,
        })
    return out
