/**
 * Deterministic renderers (Sprint 2A.6 / PR4 + GitHub export hardening sprint).
 *
 * Turn a `BuildSquadArtifactPack` (+ optional venture context) into a fixed
 * set of Markdown files that can be committed straight to a GitHub repo, and
 * synthesize the cross-cutting `EvaluationReport` artifact + its Markdown
 * twin (EVALUATION_REPORT.md).
 *
 * Two entry points:
 *   - `renderPack(pack)` — the legacy 5-file scaffold (README/PRD/ARCH/ROADMAP/USER_STORIES).
 *     Kept for back-compat; downstream callers (jobs, UI) now use renderRepoScaffold.
 *   - `renderRepoScaffold(input)` — the full repo-ready file set the hardening
 *     sprint promises: README, VISION, PRD, ARCHITECTURE, ROADMAP, USER_STORIES,
 *     RISKS, EVALUATION_REPORT, DEMO_SCRIPT, docs/personas, docs/research-graph,
 *     docs/validation, docs/build-plan, .gitignore. Always the same shape;
 *     sections lacking inputs render as explicit "_Not produced in this run._"
 *     stubs so the file set is stable.
 *
 * These are pure functions: no I/O, no LLM calls, no randomness. The same
 * inputs always produce the same bytes so a re-export is a no-op commit.
 */
import type {
  BuildSquadArtifactPack,
  BuildSquadUserStory,
  BuyingCommitteeTranscript,
  EvaluationReport,
  EvaluationReportRiskItem,
  PersonaLabPersona,
  ResearchGraph,
  Venture,
  VentureArtifactKind,
  VentureReadinessScore,
  VentureRecommendation,
  VentureRisk,
} from '@foundry/contracts';

export interface ScaffoldFile {
  path: string;
  content: string;
}

// ──────────── renderPack ─────────────────────────────────────────────────

/**
 * Produce the canonical 5-file BuildSquad scaffold:
 *   README.md, PRD.md, ARCHITECTURE.md, ROADMAP.md, USER_STORIES.md
 * Every file is always emitted; sections that the pack lacks render as
 * "_Not produced in this run._" so the README is never half-empty.
 */
export function renderPack(pack: BuildSquadArtifactPack): ScaffoldFile[] {
  return [
    { path: 'README.md', content: renderReadme(pack) },
    { path: 'PRD.md', content: renderPrd(pack) },
    { path: 'ARCHITECTURE.md', content: renderArchitecture(pack) },
    { path: 'ROADMAP.md', content: renderRoadmap(pack) },
    { path: 'USER_STORIES.md', content: renderUserStories(pack) },
  ];
}

function renderReadme(pack: BuildSquadArtifactPack): string {
  const v = pack.productVision;
  const out: string[] = [];
  out.push(`# ${escTitle(v.productPromise) || 'BuildSquad scaffold'}`);
  out.push('');
  out.push(`> Generated by Foundry BuildSquad on ${pack.createdAt} (mode: \`${pack.mode}\`).`);
  out.push('');
  out.push('## Problem');
  out.push(v.problem || '_No problem statement._');
  out.push('');
  out.push('## Target users');
  out.push(...bullets(v.targetUsers));
  out.push('');
  out.push('## Why now');
  out.push(v.whyNow || '_Not specified._');
  out.push('');
  out.push('## Differentiation');
  out.push(...bullets(v.differentiation));
  out.push('');
  out.push('## Success metrics');
  out.push(...bullets(v.successMetrics));
  out.push('');
  out.push('## Repo contents');
  out.push('- [VISION.md](./VISION.md) — Product vision (problem, promise, differentiation)');
  out.push('- [PRD.md](./PRD.md) — Product requirements document');
  out.push('- [ARCHITECTURE.md](./ARCHITECTURE.md) — System architecture brief');
  out.push('- [ROADMAP.md](./ROADMAP.md) — 4-week roadmap + MVP scope');
  out.push('- [USER_STORIES.md](./USER_STORIES.md) — Prioritised user-story backlog');
  out.push('- [RISKS.md](./RISKS.md) — Risk register');
  out.push('- [EVALUATION_REPORT.md](./EVALUATION_REPORT.md) — Readiness + decision rationale');
  out.push('- [DEMO_SCRIPT.md](./DEMO_SCRIPT.md) — Suggested 5-minute walkthrough');
  out.push('- [docs/personas.md](./docs/personas.md) — Synthetic persona cards');
  out.push('- [docs/research-graph.md](./docs/research-graph.md) — Research graph summary');
  out.push('- [docs/validation.md](./docs/validation.md) — Validation decision & evidence');
  out.push('- [docs/build-plan.md](./docs/build-plan.md) — Build-plan index');
  out.push('');
  out.push('> Generated by [Foundry](https://github.com/amit1858/foundry). Re-running export is idempotent.');
  out.push('');
  return out.join('\n');
}

function renderPrd(pack: BuildSquadArtifactPack): string {
  const out: string[] = ['# Product Requirements Document', ''];
  if (!pack.prd) {
    out.push('_PRD not produced in this run._');
    return out.join('\n');
  }
  const prd = pack.prd;
  out.push('## Overview', prd.overview || '_No overview._', '');
  out.push('## Goals', ...bullets(prd.goals), '');
  out.push('## Non-goals', ...bullets(prd.nonGoals), '');
  out.push('## Personas');
  if (prd.personas.length === 0) out.push('_None captured._');
  for (const p of prd.personas) out.push(`- **${p.name}** — ${p.summary}`);
  out.push('');
  out.push('## Requirements');
  if (prd.requirements.length === 0) out.push('_None captured._');
  for (const r of prd.requirements) {
    out.push(`- \`${r.id}\` (${r.type}) — ${r.text}${r.rationale ? ` _— ${r.rationale}_` : ''}`);
  }
  out.push('');
  out.push('## User journeys');
  if (prd.userJourneys.length === 0) out.push('_None captured._');
  for (const j of prd.userJourneys) {
    out.push(`### ${j.title}${j.personaId ? ` _(${j.personaId})_` : ''}`);
    for (let i = 0; i < j.steps.length; i++) out.push(`${i + 1}. ${j.steps[i]}`);
    out.push('');
  }
  out.push('## Metrics', ...bullets(prd.metrics), '');
  out.push('## Risks', ...bullets(prd.risks), '');
  return out.join('\n');
}

function renderArchitecture(pack: BuildSquadArtifactPack): string {
  const out: string[] = ['# Architecture brief', ''];
  if (!pack.architectureBrief) {
    out.push('_Architecture brief not produced in this run._');
    return out.join('\n');
  }
  const a = pack.architectureBrief;
  out.push('## Components');
  if (a.components.length === 0) out.push('_None captured._');
  for (const c of a.components) out.push(`- **${c.name}** — ${c.responsibility}`);
  out.push('');
  out.push('## Data flow', ...bullets(a.dataFlow), '');
  out.push('## Integrations', ...bullets(a.integrations), '');
  out.push('## Storage', ...bullets(a.storage), '');
  out.push('## Security', ...bullets(a.security), '');
  out.push('## Scalability assumptions', ...bullets(a.scalabilityAssumptions), '');
  return out.join('\n');
}

function renderRoadmap(pack: BuildSquadArtifactPack): string {
  const out: string[] = ['# 4-week roadmap', ''];
  if (!pack.roadmap) {
    out.push('_Roadmap not produced in this run._');
    return out.join('\n');
  }
  for (const w of pack.roadmap.weeks) {
    out.push(`## Week ${w.week} — ${w.theme}`);
    out.push(...bullets(w.deliverables));
    out.push('');
  }
  out.push('## Future backlog', ...bullets(pack.roadmap.futureBacklog), '');
  if (pack.mvpScope) {
    out.push('## MVP scope');
    out.push('### Must-have', ...bullets(pack.mvpScope.mustHave), '');
    out.push('### Should-have', ...bullets(pack.mvpScope.shouldHave), '');
    out.push('### Later', ...bullets(pack.mvpScope.later), '');
    if (pack.mvpScope.explicitCuts.length > 0) {
      out.push('### Explicit cuts');
      for (const c of pack.mvpScope.explicitCuts) out.push(`- **${c.item}** — ${c.reason}`);
      out.push('');
    }
  }
  return out.join('\n');
}

function renderUserStories(pack: BuildSquadArtifactPack): string {
  const out: string[] = ['# User stories', ''];
  if (!pack.userStories || pack.userStories.length === 0) {
    out.push('_No user stories produced in this run._');
    return out.join('\n');
  }
  const grouped: Record<BuildSquadUserStory['priority'], BuildSquadUserStory[]> = {
    must: [], should: [], later: [],
  };
  for (const s of pack.userStories) grouped[s.priority].push(s);
  for (const [priority, label] of [['must', 'Must-have'], ['should', 'Should-have'], ['later', 'Later']] as const) {
    const list = grouped[priority];
    if (list.length === 0) continue;
    out.push(`## ${label}`, '');
    for (const s of list) {
      out.push(`### \`${s.id}\` — ${s.title}${s.personaId ? ` _(${s.personaId})_` : ''}`);
      out.push(`> ${s.story}`, '');
      out.push('**Acceptance criteria**');
      out.push(...bullets(s.acceptanceCriteria));
      out.push('');
    }
  }
  return out.join('\n');
}

// ──────────── renderRepoScaffold ─────────────────────────────────────────
//
// Full repo-ready file set. Always emits the same paths so a re-export is a
// no-op commit. Sections without inputs render explicit "_Not produced in
// this run._" stubs.

export interface RenderRepoScaffoldInput {
  venture: Venture;
  pack: BuildSquadArtifactPack;
  recommendation: VentureRecommendation | null;
  personas: PersonaLabPersona[] | null;
  graph: ResearchGraph | null;
  committee: BuyingCommitteeTranscript | null;
  /** Pre-rendered EVALUATION_REPORT.md text. */
  evaluationMarkdown: string;
  /** Optional venture summary readiness, for the build-plan index. */
  readiness?: VentureReadinessScore;
}

/**
 * Produce the full 14-file repo scaffold the GitHub export hardening sprint
 * promises. Order is deterministic.
 */
export function renderRepoScaffold(input: RenderRepoScaffoldInput): ScaffoldFile[] {
  const { pack } = input;
  const baseFiles = renderPack(pack); // README + PRD + ARCHITECTURE + ROADMAP + USER_STORIES
  return [
    ...baseFiles,
    { path: 'VISION.md', content: renderVision(pack) },
    { path: 'RISKS.md', content: renderRisks(input) },
    { path: 'EVALUATION_REPORT.md', content: input.evaluationMarkdown },
    { path: 'DEMO_SCRIPT.md', content: renderDemoScript(input) },
    { path: 'docs/personas.md', content: renderPersonasDoc(input.personas) },
    { path: 'docs/research-graph.md', content: renderResearchGraphDoc(input.graph) },
    { path: 'docs/validation.md', content: renderValidationDoc(input.recommendation, input.committee) },
    { path: 'docs/build-plan.md', content: renderBuildPlanDoc(pack, input.readiness) },
    { path: '.gitignore', content: renderGitignore() },
  ];
}

function renderVision(pack: BuildSquadArtifactPack): string {
  const v = pack.productVision;
  const out: string[] = ['# Product vision', ''];
  out.push(`> Generated by Foundry BuildSquad on ${pack.createdAt} (mode: \`${pack.mode}\`).`);
  out.push('');
  out.push('## Product promise');
  out.push(v.productPromise || '_Not specified._');
  out.push('');
  out.push('## Problem');
  out.push(v.problem || '_No problem statement._');
  out.push('');
  out.push('## Target users');
  out.push(...bullets(v.targetUsers));
  out.push('');
  out.push('## Why now');
  out.push(v.whyNow || '_Not specified._');
  out.push('');
  out.push('## Differentiation');
  out.push(...bullets(v.differentiation));
  out.push('');
  out.push('## Success metrics');
  out.push(...bullets(v.successMetrics));
  out.push('');
  return out.join('\n');
}

function renderRisks(input: RenderRepoScaffoldInput): string {
  const out: string[] = ['# Risk register', ''];
  const rec = input.recommendation;
  const recRisks = rec?.risks ?? [];
  const contradictions = input.graph?.contradictions ?? [];
  const critiques = input.pack.agentCritiques ?? [];

  if (recRisks.length === 0 && contradictions.length === 0 && critiques.length === 0) {
    out.push('_No risks captured. Run VentureLab and BuildSquad to surface assumptions and counter-signals._');
    return out.join('\n');
  }

  if (recRisks.length > 0) {
    out.push('## Validation risks');
    out.push('| Risk | Impact | Likelihood | Mitigation |');
    out.push('| --- | --- | --- | --- |');
    for (const r of recRisks) {
      out.push(`| ${escapeCell(r.risk)} | ${r.impact} | ${r.likelihood} | ${escapeCell(r.mitigation || '_TBD_')} |`);
    }
    out.push('');
  }

  if (contradictions.length > 0) {
    out.push('## Research contradictions');
    for (const c of contradictions) out.push(`- ${c}`);
    out.push('');
  }

  const blockers = critiques.filter((c) => c.severity === 'blocker');
  const warnings = critiques.filter((c) => c.severity === 'warning');
  if (blockers.length + warnings.length > 0) {
    out.push('## Build-plan critiques');
    for (const c of [...blockers, ...warnings]) {
      out.push(`- **[${c.severity}] ${c.role} → ${c.targetSection}** — ${c.comment}${c.suggestion ? ` _Suggestion:_ ${c.suggestion}` : ''}`);
    }
    out.push('');
  }
  return out.join('\n');
}

function renderDemoScript(input: RenderRepoScaffoldInput): string {
  const v = input.pack.productVision;
  const rec = input.recommendation;
  const personas = input.personas ?? [];
  const stories = input.pack.userStories ?? [];
  const must = stories.filter((s) => s.priority === 'must').slice(0, 3);

  const out: string[] = [`# Demo script — ${input.venture.title}`, ''];
  out.push('> A suggested 5-minute walkthrough of this venture.');
  out.push('> Generated by Foundry; edit freely once you have a real recording.');
  out.push('');
  out.push('## 0:00 — Problem');
  out.push(v.problem || '_Problem statement not captured._');
  out.push('');
  out.push('## 0:45 — Who feels it');
  if (personas.length === 0) {
    out.push('_No personas attached._');
  } else {
    for (const p of personas.slice(0, 3)) out.push(`- **${p.name}** (${p.role}) — "${p.quote || p.goals[0] || ''}"`);
  }
  out.push('');
  out.push('## 1:30 — Our promise');
  out.push(v.productPromise || '_Not specified._');
  out.push('');
  out.push('## 2:15 — Why now');
  out.push(v.whyNow || '_Not specified._');
  out.push('');
  out.push('## 3:00 — Live walkthrough (3 must-have stories)');
  if (must.length === 0) {
    out.push('_No must-have user stories captured — generate a BuildSquad pack to populate this._');
  } else {
    for (const s of must) out.push(`- \`${s.id}\` ${s.title}`);
  }
  out.push('');
  out.push('## 4:00 — The decision');
  if (rec) {
    out.push(`- **VentureLab recommendation:** ${rec.decision} (score ${rec.overallScore}/100, confidence ${(rec.confidenceScore * 100).toFixed(0)}%).`);
    if (rec.decisionRationale.length > 0) {
      out.push('- Top rationale:');
      for (const r of rec.decisionRationale.slice(0, 3)) out.push(`  - ${r}`);
    }
  } else {
    out.push('_No VentureLab recommendation yet — run VentureLab and re-export to populate._');
  }
  out.push('');
  out.push('## 4:30 — What we built next');
  out.push(`- See [PRD.md](./PRD.md), [ROADMAP.md](./ROADMAP.md), [USER_STORIES.md](./USER_STORIES.md).`);
  out.push(`- See [EVALUATION_REPORT.md](./EVALUATION_REPORT.md) for the readiness scorecard.`);
  out.push('');
  return out.join('\n');
}

function renderPersonasDoc(personas: PersonaLabPersona[] | null): string {
  const out: string[] = ['# Personas', ''];
  if (!personas || personas.length === 0) {
    out.push('_No persona set attached. Generate one in PersonaLab and re-export._');
    return out.join('\n');
  }
  out.push(`> ${personas.length} synthetic persona${personas.length === 1 ? '' : 's'} from PersonaLab.`);
  out.push('');
  for (const p of personas) {
    out.push(`## ${p.name} — ${p.role}`);
    if (p.businessContext) out.push(`> _${p.businessContext}_`);
    if (p.quote) out.push('', `“${p.quote}”`);
    out.push('');
    out.push(`- **Decision power:** ${p.decisionPower}`);
    out.push(`- **Confidence:** ${(p.confidenceScore * 100).toFixed(0)}%`);
    if (p.goals.length > 0) {
      out.push('- **Goals:**');
      for (const g of p.goals) out.push(`  - ${g}`);
    }
    if (p.painPoints.length > 0) {
      out.push('- **Pain points:**');
      for (const x of p.painPoints) out.push(`  - ${x}`);
    }
    if (p.motivations.length > 0) {
      out.push('- **Motivations:**');
      for (const m of p.motivations) out.push(`  - ${m}`);
    }
    if (p.objections.length > 0) {
      out.push('- **Objections:**');
      for (const o of p.objections) out.push(`  - ${o}`);
    }
    if (p.buyingTriggers.length > 0) {
      out.push('- **Buying triggers:**');
      for (const t of p.buyingTriggers) out.push(`  - ${t}`);
    }
    out.push('');
  }
  return out.join('\n');
}

function renderResearchGraphDoc(graph: ResearchGraph | null): string {
  const out: string[] = ['# Research graph', ''];
  if (!graph) {
    out.push('_No research graph attached. Run Graphify and re-export._');
    return out.join('\n');
  }
  const nodes = graph.stats?.nodes ?? graph.nodes?.length ?? 0;
  const edges = graph.stats?.edges ?? graph.edges?.length ?? 0;
  const communities = graph.stats?.communities ?? 0;
  out.push(`> ${nodes} nodes · ${edges} edges · ${communities} communities.`);
  out.push('');

  if (graph.godNodes && graph.godNodes.length > 0) {
    out.push('## Top god-nodes');
    out.push('| Label | Degree | Community |');
    out.push('| --- | --- | --- |');
    for (const g of graph.godNodes.slice(0, 10)) {
      out.push(`| ${escapeCell(g.label)} | ${g.degree} | ${g.community} |`);
    }
    out.push('');
  }

  if (graph.contradictions && graph.contradictions.length > 0) {
    out.push('## Contradictions');
    for (const c of graph.contradictions) out.push(`- ${c}`);
    out.push('');
  }

  if (graph.surprisingConnections && graph.surprisingConnections.length > 0) {
    out.push('## Surprising connections');
    for (const c of graph.surprisingConnections) out.push(`- ${c}`);
    out.push('');
  }

  if (graph.sources && graph.sources.length > 0) {
    out.push('## Sources');
    for (const s of graph.sources.slice(0, 20)) {
      const label = (s as { title?: string; url?: string; id?: string }).title
        ?? (s as { title?: string; url?: string; id?: string }).url
        ?? (s as { title?: string; url?: string; id?: string }).id
        ?? 'source';
      out.push(`- ${label}`);
    }
    out.push('');
  }
  return out.join('\n');
}

function renderValidationDoc(
  rec: VentureRecommendation | null,
  committee: BuyingCommitteeTranscript | null,
): string {
  const out: string[] = ['# Validation', ''];
  if (!rec) {
    out.push('_No VentureLab recommendation yet. Run VentureLab and re-export._');
    return out.join('\n');
  }
  out.push(`## Decision: ${rec.decision}`);
  out.push(`- **Overall score:** ${rec.overallScore}/100`);
  out.push(`- **Confidence:** ${(rec.confidenceScore * 100).toFixed(0)}%`);
  out.push('');
  out.push('## Executive summary');
  out.push(rec.executiveSummary || '_Not specified._');
  out.push('');
  if (rec.decisionRationale.length > 0) {
    out.push('## Decision rationale');
    for (const r of rec.decisionRationale) out.push(`- ${r}`);
    out.push('');
  }
  if (rec.scores.length > 0) {
    out.push('## Scorecard');
    out.push('| Dimension | Score | Direction | Explanation |');
    out.push('| --- | --- | --- | --- |');
    for (const s of rec.scores) {
      out.push(`| ${s.dimension} | ${s.score} | ${s.higherIsBetter ? 'higher = better' : 'lower = better'} | ${escapeCell(s.explanation)} |`);
    }
    out.push('');
  }
  if (rec.evidence.length > 0) {
    out.push('## Evidence');
    for (const e of rec.evidence.slice(0, 10)) {
      out.push(`- _${e.source}_ (weight ${e.weight}) — "${e.quote}"`);
    }
    out.push('');
  }
  if (rec.counterSignals.length > 0) {
    out.push('## Counter-signals');
    for (const e of rec.counterSignals.slice(0, 10)) {
      out.push(`- _${e.source}_ (weight ${e.weight}) — "${e.quote}"`);
    }
    out.push('');
  }
  if (rec.assumptions.length > 0) {
    out.push('## Assumptions');
    for (const a of rec.assumptions) {
      out.push(`- \`${a.id}\` (${a.type}, ${a.confidence}) — ${a.text}${a.validationStrategy ? ` _Validation:_ ${a.validationStrategy}` : ''}`);
    }
    out.push('');
  }
  if (rec.nextSteps.length > 0) {
    out.push('## Next steps');
    for (const s of rec.nextSteps) {
      out.push(`- _(${s.category}, p${s.priority}, effort ${s.effort})_ ${s.title}${s.blocksDecision ? ' **— blocks decision**' : ''}`);
    }
    out.push('');
  }
  if (committee) {
    out.push('## Buying committee');
    out.push(`- **Decision:** ${committee.decision}`);
    if (committee.decisionRationale) out.push(`- **Rationale:** ${committee.decisionRationale}`);
    if (committee.nextSteps.length > 0) {
      out.push('- **Next steps:**');
      for (const s of committee.nextSteps) out.push(`  - ${s}`);
    }
    out.push('');
  }
  return out.join('\n');
}

function renderBuildPlanDoc(
  pack: BuildSquadArtifactPack,
  readiness: VentureReadinessScore | undefined,
): string {
  const out: string[] = ['# Build plan', ''];
  out.push(`> BuildSquad mode: \`${pack.mode}\` · generated ${pack.createdAt}.`);
  out.push('');
  if (readiness) {
    out.push('## Readiness snapshot');
    out.push(`- **Overall:** ${readiness.overall}/100`);
    out.push(`- Persona coverage: ${readiness.personaCoverage}`);
    out.push(`- Research coverage: ${readiness.researchCoverage}`);
    out.push(`- Validation confidence: ${readiness.validationConfidence}`);
    out.push(`- BuildSquad completeness: ${readiness.buildsquadCompleteness}`);
    out.push(`- Risk coverage: ${readiness.riskCoverage}`);
    out.push('');
  }
  out.push('## Sections');
  out.push('- [PRD.md](./PRD.md) — Goals, requirements, journeys, metrics, risks.');
  out.push('- [ARCHITECTURE.md](./ARCHITECTURE.md) — Components, data flow, integrations, security.');
  out.push('- [ROADMAP.md](./ROADMAP.md) — 4-week roadmap + MVP scope.');
  out.push('- [USER_STORIES.md](./USER_STORIES.md) — Must/should/later stories with acceptance criteria.');
  out.push('- [RISKS.md](./RISKS.md) — Risk register.');
  if (pack.prototypeBrief) {
    out.push('');
    out.push('## Prototype brief');
    if (pack.prototypeBrief.pages.length > 0) {
      out.push('### Pages');
      for (const p of pack.prototypeBrief.pages) out.push(`- **${p.name}** — ${p.purpose}`);
    }
    if (pack.prototypeBrief.flows.length > 0) {
      out.push('### Flows');
      for (const f of pack.prototypeBrief.flows) {
        out.push(`- **${f.name}**`);
        for (const s of f.steps) out.push(`  - ${s}`);
      }
    }
    if (pack.prototypeBrief.uiComponents.length > 0) {
      out.push('### UI components');
      out.push(...bullets(pack.prototypeBrief.uiComponents));
    }
    if (pack.prototypeBrief.demoScenario) {
      out.push('### Demo scenario');
      out.push(pack.prototypeBrief.demoScenario);
    }
    out.push('');
  }
  if (pack.agentCritiques.length > 0) {
    out.push('## Agent critiques');
    for (const c of pack.agentCritiques) {
      out.push(`- _[${c.severity}] ${c.role} → ${c.targetSection}_ — ${c.comment}${c.suggestion ? ` _Suggestion:_ ${c.suggestion}` : ''}`);
    }
    out.push('');
  }
  if (pack.rationale.length > 0) {
    out.push('## Orchestrator notes');
    for (const r of pack.rationale) out.push(`- ${r}`);
    out.push('');
  }
  return out.join('\n');
}

function renderGitignore(): string {
  return [
    '# Foundry-generated repo scaffold',
    '',
    '# Node',
    'node_modules/',
    'npm-debug.log*',
    'yarn-debug.log*',
    'yarn-error.log*',
    'pnpm-debug.log*',
    '.pnpm-store/',
    '',
    '# Build outputs',
    'dist/',
    'build/',
    '.next/',
    '.turbo/',
    '',
    '# Env / secrets — never commit',
    '.env',
    '.env.*',
    '!.env.example',
    '',
    '# IDE',
    '.vscode/',
    '.idea/',
    '',
    '# OS',
    '.DS_Store',
    'Thumbs.db',
    '',
  ].join('\n');
}

function escapeCell(s: string): string {
  return (s ?? '').replace(/\n+/g, ' ').replace(/\|/g, '\\|');
}

// ──────────── renderEvaluationReport ─────────────────────────────────────

export interface RenderEvaluationReportInput {
  venture: Venture;
  pack: BuildSquadArtifactPack | null;
  recommendation: VentureRecommendation | null;
  personas: PersonaLabPersona[] | null;
  graph: ResearchGraph | null;
  committee: BuyingCommitteeTranscript | null;
  readiness: VentureReadinessScore;
  /** Stable, monotonic generator id for change tracking. */
  generatorVersion?: string;
  /** Provenance: which source artifact versions fed the report. */
  sourceArtifacts?: { kind: VentureArtifactKind; version: number }[];
  /** Override clock (tests). */
  now?: () => Date;
}

export interface RenderEvaluationReportOutput {
  artifact: EvaluationReport;
  /** Single-file Markdown render destined for EVALUATION_REPORT.md. */
  markdown: string;
}

export function renderEvaluationReport(input: RenderEvaluationReportInput): RenderEvaluationReportOutput {
  const generatedAt = (input.now ?? (() => new Date()))().toISOString();
  const generatorVersion = input.generatorVersion ?? 'evaluation-report@1';

  const personaCount = input.personas?.length ?? 0;
  const personaCoverage = {
    score: clamp01(personaCount === 0 ? 0 : Math.min(1, personaCount / 5)),
    count: personaCount,
    notes: personaNotes(input.personas),
  };

  const nodeCount = input.graph?.stats?.nodes ?? 0;
  const godNodeCount = input.graph?.godNodes?.length ?? 0;
  const contradictionCount = input.graph?.contradictions?.length ?? 0;
  const researchCoverage = {
    score: clamp01(nodeCount === 0 ? 0 : Math.min(1, nodeCount / 40)),
    nodeCount,
    godNodeCount,
    contradictionCount,
    topGodNodes: (input.graph?.godNodes ?? []).slice(0, 5).map((n) => ({
      label: n.label,
      weight: n.degree,
    })),
    notes: researchNotes(input.graph),
  };

  const risks = collectRisks(input.recommendation, input.committee, input.graph);
  const contradictionsPairs: { left: string; right: string }[] = (input.graph?.contradictions ?? []).map((c) => {
    const [left, right] = c.split('↔').map((s) => s.trim());
    return { left: left ?? c, right: right ?? '' };
  });
  const riskCoverage = {
    score: clamp01(risks.length === 0 ? 0 : Math.min(1, risks.length / 5)),
    identifiedRisks: risks,
    contradictions: contradictionsPairs,
    notes: riskNotes(risks, contradictionsPairs),
  };

  const rec = input.recommendation;
  const assumptions = (rec?.assumptions ?? []).map((a) => a.text);
  const openQuestions = (rec?.nextSteps ?? [])
    .filter((s) => s.blocksDecision)
    .map((s) => s.title);
  const validationRoadmap = {
    nextSteps: (rec?.nextSteps ?? []).slice(0, 8).map((s) => ({
      label: s.title,
      ...(s.category ? { owner: s.category } : {}),
    })),
    successCriteria: deriveSuccessCriteria(input.pack),
    killCriteria: deriveKillCriteria(rec),
  };

  const artifact: EvaluationReport = {
    kind: 'EvaluationReport',
    reportId: `er_${input.venture.ventureId}_${generatedAt.replace(/[^0-9]/g, '').slice(0, 14)}`,
    ventureId: input.venture.ventureId,
    generatedAt,
    generatorVersion,
    venture: {
      id: input.venture.ventureId,
      title: input.venture.title,
      status: input.venture.status,
      ...(input.venture.region ? { region: input.venture.region } : {}),
      ...(input.venture.customerType ? { customerType: input.venture.customerType } : {}),
    },
    readinessScore: input.readiness,
    recommendation: {
      decision: rec?.decision ?? null,
      confidence: rec?.confidenceScore ?? null,
      rationale: rec?.decisionRationale ?? [],
      ...(rec?.decision === 'PIVOT' && input.pack?.pivot
        ? { pivotOptions: [input.pack.pivot.revisedMvpDirection] }
        : {}),
    },
    coverage: {
      persona: personaCoverage,
      research: researchCoverage,
      risk: riskCoverage,
    },
    assumptions,
    openQuestions,
    validationRoadmap,
    provenance: {
      sourceArtifacts: input.sourceArtifacts ?? [],
    },
  };

  return { artifact, markdown: renderEvaluationMarkdown(artifact) };
}

function renderEvaluationMarkdown(r: EvaluationReport): string {
  const out: string[] = [];
  out.push(`# Evaluation report — ${r.venture.title}`);
  out.push('');
  out.push(`> Generated ${r.generatedAt} · \`${r.generatorVersion}\``);
  out.push('');
  out.push('## Readiness score');
  out.push(`- **Overall:** ${r.readinessScore.overall} / 100`);
  out.push(`- Persona coverage: ${r.readinessScore.personaCoverage}`);
  out.push(`- Research coverage: ${r.readinessScore.researchCoverage}`);
  out.push(`- Validation confidence: ${r.readinessScore.validationConfidence}`);
  out.push(`- BuildSquad completeness: ${r.readinessScore.buildsquadCompleteness}`);
  out.push(`- Risk coverage: ${r.readinessScore.riskCoverage}`);
  if (r.readinessScore.warnings.length > 0) {
    out.push('', '**Warnings**');
    out.push(...bullets(r.readinessScore.warnings));
  }
  out.push('');
  out.push('## Recommendation');
  out.push(`- **Decision:** ${r.recommendation.decision ?? '_none yet_'}`);
  if (r.recommendation.confidence != null) {
    out.push(`- Confidence: ${(r.recommendation.confidence * 100).toFixed(0)}%`);
  }
  if (r.recommendation.rationale.length > 0) {
    out.push('', '### Rationale');
    out.push(...bullets(r.recommendation.rationale));
  }
  if (r.recommendation.pivotOptions && r.recommendation.pivotOptions.length > 0) {
    out.push('', '### Pivot direction');
    out.push(...bullets(r.recommendation.pivotOptions));
  }
  out.push('');
  out.push('## Coverage');
  out.push(`- Persona: ${(r.coverage.persona.score * 100).toFixed(0)}% (${r.coverage.persona.count} personas)`);
  out.push(...indentBullets(r.coverage.persona.notes));
  out.push(`- Research: ${(r.coverage.research.score * 100).toFixed(0)}% (${r.coverage.research.nodeCount} nodes, ${r.coverage.research.godNodeCount} god-nodes, ${r.coverage.research.contradictionCount} contradictions)`);
  if (r.coverage.research.topGodNodes.length > 0) {
    out.push('  - Top god-nodes:');
    for (const g of r.coverage.research.topGodNodes) out.push(`    - ${g.label} (weight ${g.weight})`);
  }
  out.push(...indentBullets(r.coverage.research.notes));
  out.push(`- Risk: ${(r.coverage.risk.score * 100).toFixed(0)}% (${r.coverage.risk.identifiedRisks.length} risks)`);
  for (const risk of r.coverage.risk.identifiedRisks) {
    out.push(`  - _${risk.severity}_ (${risk.source}) — ${risk.label}`);
  }
  if (r.coverage.risk.contradictions.length > 0) {
    out.push('  - Contradictions:');
    for (const c of r.coverage.risk.contradictions) out.push(`    - ${c.left}${c.right ? ` ↔ ${c.right}` : ''}`);
  }
  out.push('');
  if (r.assumptions.length > 0) {
    out.push('## Assumptions');
    out.push(...bullets(r.assumptions));
    out.push('');
  }
  if (r.openQuestions.length > 0) {
    out.push('## Open questions');
    out.push(...bullets(r.openQuestions));
    out.push('');
  }
  out.push('## Validation roadmap');
  out.push('### Next steps');
  if (r.validationRoadmap.nextSteps.length === 0) out.push('_None._');
  for (const s of r.validationRoadmap.nextSteps) {
    out.push(`- ${s.label}${s.owner ? ` _(${s.owner})_` : ''}`);
  }
  out.push('', '### Success criteria');
  out.push(...bullets(r.validationRoadmap.successCriteria));
  out.push('', '### Kill criteria');
  out.push(...bullets(r.validationRoadmap.killCriteria));
  out.push('');
  if (r.provenance.sourceArtifacts.length > 0) {
    out.push('## Provenance');
    for (const s of r.provenance.sourceArtifacts) out.push(`- ${s.kind} v${s.version}`);
    out.push('');
  }
  return out.join('\n');
}

// ──────────── helpers ────────────────────────────────────────────────────

function bullets(items: string[] | undefined): string[] {
  if (!items || items.length === 0) return ['_None._'];
  return items.map((i) => `- ${i}`);
}

function indentBullets(items: string[]): string[] {
  return items.map((i) => `  - ${i}`);
}

function escTitle(s: string): string {
  return s.replace(/[\r\n]+/g, ' ').slice(0, 120);
}

function clamp01(x: number): number {
  if (!Number.isFinite(x)) return 0;
  return Math.max(0, Math.min(1, x));
}

function personaNotes(personas: PersonaLabPersona[] | null): string[] {
  if (!personas || personas.length === 0) return ['No persona set attached.'];
  const notes: string[] = [];
  notes.push(`${personas.length} persona${personas.length === 1 ? '' : 's'} on file.`);
  return notes;
}

function researchNotes(graph: ResearchGraph | null): string[] {
  if (!graph) return ['No research graph attached.'];
  const notes: string[] = [];
  if ((graph.stats?.nodes ?? 0) < 10) notes.push('Graph is sparse (<10 nodes).');
  if ((graph.contradictions?.length ?? 0) > 0) notes.push('Contradictions detected — review before proceeding.');
  return notes;
}

function riskNotes(risks: EvaluationReportRiskItem[], contradictions: { left: string; right: string }[]): string[] {
  const notes: string[] = [];
  if (risks.length === 0) notes.push('No risks identified — check recommendation/committee coverage.');
  const highs = risks.filter((r) => r.severity === 'high').length;
  if (highs > 0) notes.push(`${highs} high-severity risk${highs === 1 ? '' : 's'}.`);
  if (contradictions.length > 0) notes.push(`${contradictions.length} contradiction${contradictions.length === 1 ? '' : 's'} unresolved.`);
  return notes;
}

function collectRisks(
  rec: VentureRecommendation | null,
  committee: BuyingCommitteeTranscript | null,
  graph: ResearchGraph | null,
): EvaluationReportRiskItem[] {
  const out: EvaluationReportRiskItem[] = [];
  if (rec) {
    for (const r of rec.risks) out.push({ label: r.risk, severity: mapSeverity(r), source: 'recommendation' });
  }
  if (committee) {
    const objections = (committee as unknown as { objections?: string[] }).objections ?? [];
    for (const o of objections.slice(0, 5)) out.push({ label: o, severity: 'med', source: 'committee' });
  }
  if (graph?.contradictions) {
    for (const c of graph.contradictions.slice(0, 3)) {
      out.push({ label: `Contradiction: ${c}`, severity: 'med', source: 'graph' });
    }
  }
  return out;
}

function mapSeverity(r: VentureRisk): EvaluationReportRiskItem['severity'] {
  const impact = r.impact === 'high' ? 2 : r.impact === 'medium' ? 1 : 0;
  const likelihood = r.likelihood === 'high' ? 2 : r.likelihood === 'medium' ? 1 : 0;
  const score = impact + likelihood;
  if (score >= 3) return 'high';
  if (score >= 2) return 'med';
  return 'low';
}

function deriveSuccessCriteria(pack: BuildSquadArtifactPack | null): string[] {
  if (!pack) return ['_No BuildSquad pack — define success metrics during planning._'];
  return pack.productVision.successMetrics.length > 0
    ? pack.productVision.successMetrics
    : ['_Pack present but no success metrics captured._'];
}

function deriveKillCriteria(rec: VentureRecommendation | null): string[] {
  if (!rec) return ['_No recommendation yet — define kill criteria during validation._'];
  if (rec.decision === 'KILL') return rec.decisionRationale.slice(0, 5);
  return rec.nextSteps
    .filter((s) => s.blocksDecision)
    .slice(0, 5)
    .map((s) => `Kill if blocked by: ${s.title}`);
}
