/**
 * Deterministic renderers (Sprint 2A.6 / PR4).
 *
 * Turn a `BuildSquadArtifactPack` (+ optional venture context) into a fixed
 * set of Markdown files that can be committed straight to a GitHub repo, and
 * synthesize the cross-cutting `EvaluationReport` artifact + its Markdown
 * twin (EVALUATION_REPORT.md).
 *
 * These are pure functions: no I/O, no LLM calls, no randomness. The same
 * inputs always produce the same bytes so a re-export is a no-op commit.
 */
import type {
  BuildSquadArtifactPack,
  BuildSquadUserStory,
  BuyingCommitteeTranscript,
  EvaluationReport,
  EvaluationReportRiskItem,
  PersonaLabPersona,
  ResearchGraph,
  Venture,
  VentureArtifactKind,
  VentureReadinessScore,
  VentureRecommendation,
  VentureRisk,
} from '@ventureos/contracts';

export interface ScaffoldFile {
  path: string;
  content: string;
}

// ──────────── renderPack ─────────────────────────────────────────────────

/**
 * Produce the canonical 5-file BuildSquad scaffold:
 *   README.md, PRD.md, ARCHITECTURE.md, ROADMAP.md, USER_STORIES.md
 * Every file is always emitted; sections that the pack lacks render as
 * "_Not produced in this run._" so the README is never half-empty.
 */
export function renderPack(pack: BuildSquadArtifactPack): ScaffoldFile[] {
  return [
    { path: 'README.md', content: renderReadme(pack) },
    { path: 'PRD.md', content: renderPrd(pack) },
    { path: 'ARCHITECTURE.md', content: renderArchitecture(pack) },
    { path: 'ROADMAP.md', content: renderRoadmap(pack) },
    { path: 'USER_STORIES.md', content: renderUserStories(pack) },
  ];
}

function renderReadme(pack: BuildSquadArtifactPack): string {
  const v = pack.productVision;
  const out: string[] = [];
  out.push(`# ${escTitle(v.productPromise) || 'BuildSquad scaffold'}`);
  out.push('');
  out.push(`> Generated by VentureOS BuildSquad on ${pack.createdAt} (mode: \`${pack.mode}\`).`);
  out.push('');
  out.push('## Problem');
  out.push(v.problem || '_No problem statement._');
  out.push('');
  out.push('## Target users');
  out.push(...bullets(v.targetUsers));
  out.push('');
  out.push('## Why now');
  out.push(v.whyNow || '_Not specified._');
  out.push('');
  out.push('## Differentiation');
  out.push(...bullets(v.differentiation));
  out.push('');
  out.push('## Success metrics');
  out.push(...bullets(v.successMetrics));
  out.push('');
  out.push('## Repo contents');
  out.push('- [PRD.md](./PRD.md) — Product requirements');
  out.push('- [ARCHITECTURE.md](./ARCHITECTURE.md) — System brief');
  out.push('- [ROADMAP.md](./ROADMAP.md) — 4-week plan');
  out.push('- [USER_STORIES.md](./USER_STORIES.md) — Backlog seed');
  out.push('- [EVALUATION_REPORT.md](./EVALUATION_REPORT.md) — Readiness + decision rationale');
  out.push('');
  return out.join('\n');
}

function renderPrd(pack: BuildSquadArtifactPack): string {
  const out: string[] = ['# Product Requirements Document', ''];
  if (!pack.prd) {
    out.push('_PRD not produced in this run._');
    return out.join('\n');
  }
  const prd = pack.prd;
  out.push('## Overview', prd.overview || '_No overview._', '');
  out.push('## Goals', ...bullets(prd.goals), '');
  out.push('## Non-goals', ...bullets(prd.nonGoals), '');
  out.push('## Personas');
  if (prd.personas.length === 0) out.push('_None captured._');
  for (const p of prd.personas) out.push(`- **${p.name}** — ${p.summary}`);
  out.push('');
  out.push('## Requirements');
  if (prd.requirements.length === 0) out.push('_None captured._');
  for (const r of prd.requirements) {
    out.push(`- \`${r.id}\` (${r.type}) — ${r.text}${r.rationale ? ` _— ${r.rationale}_` : ''}`);
  }
  out.push('');
  out.push('## User journeys');
  if (prd.userJourneys.length === 0) out.push('_None captured._');
  for (const j of prd.userJourneys) {
    out.push(`### ${j.title}${j.personaId ? ` _(${j.personaId})_` : ''}`);
    for (let i = 0; i < j.steps.length; i++) out.push(`${i + 1}. ${j.steps[i]}`);
    out.push('');
  }
  out.push('## Metrics', ...bullets(prd.metrics), '');
  out.push('## Risks', ...bullets(prd.risks), '');
  return out.join('\n');
}

function renderArchitecture(pack: BuildSquadArtifactPack): string {
  const out: string[] = ['# Architecture brief', ''];
  if (!pack.architectureBrief) {
    out.push('_Architecture brief not produced in this run._');
    return out.join('\n');
  }
  const a = pack.architectureBrief;
  out.push('## Components');
  if (a.components.length === 0) out.push('_None captured._');
  for (const c of a.components) out.push(`- **${c.name}** — ${c.responsibility}`);
  out.push('');
  out.push('## Data flow', ...bullets(a.dataFlow), '');
  out.push('## Integrations', ...bullets(a.integrations), '');
  out.push('## Storage', ...bullets(a.storage), '');
  out.push('## Security', ...bullets(a.security), '');
  out.push('## Scalability assumptions', ...bullets(a.scalabilityAssumptions), '');
  return out.join('\n');
}

function renderRoadmap(pack: BuildSquadArtifactPack): string {
  const out: string[] = ['# 4-week roadmap', ''];
  if (!pack.roadmap) {
    out.push('_Roadmap not produced in this run._');
    return out.join('\n');
  }
  for (const w of pack.roadmap.weeks) {
    out.push(`## Week ${w.week} — ${w.theme}`);
    out.push(...bullets(w.deliverables));
    out.push('');
  }
  out.push('## Future backlog', ...bullets(pack.roadmap.futureBacklog), '');
  if (pack.mvpScope) {
    out.push('## MVP scope');
    out.push('### Must-have', ...bullets(pack.mvpScope.mustHave), '');
    out.push('### Should-have', ...bullets(pack.mvpScope.shouldHave), '');
    out.push('### Later', ...bullets(pack.mvpScope.later), '');
    if (pack.mvpScope.explicitCuts.length > 0) {
      out.push('### Explicit cuts');
      for (const c of pack.mvpScope.explicitCuts) out.push(`- **${c.item}** — ${c.reason}`);
      out.push('');
    }
  }
  return out.join('\n');
}

function renderUserStories(pack: BuildSquadArtifactPack): string {
  const out: string[] = ['# User stories', ''];
  if (!pack.userStories || pack.userStories.length === 0) {
    out.push('_No user stories produced in this run._');
    return out.join('\n');
  }
  const grouped: Record<BuildSquadUserStory['priority'], BuildSquadUserStory[]> = {
    must: [], should: [], later: [],
  };
  for (const s of pack.userStories) grouped[s.priority].push(s);
  for (const [priority, label] of [['must', 'Must-have'], ['should', 'Should-have'], ['later', 'Later']] as const) {
    const list = grouped[priority];
    if (list.length === 0) continue;
    out.push(`## ${label}`, '');
    for (const s of list) {
      out.push(`### \`${s.id}\` — ${s.title}${s.personaId ? ` _(${s.personaId})_` : ''}`);
      out.push(`> ${s.story}`, '');
      out.push('**Acceptance criteria**');
      out.push(...bullets(s.acceptanceCriteria));
      out.push('');
    }
  }
  return out.join('\n');
}

// ──────────── renderEvaluationReport ─────────────────────────────────────

export interface RenderEvaluationReportInput {
  venture: Venture;
  pack: BuildSquadArtifactPack | null;
  recommendation: VentureRecommendation | null;
  personas: PersonaLabPersona[] | null;
  graph: ResearchGraph | null;
  committee: BuyingCommitteeTranscript | null;
  readiness: VentureReadinessScore;
  /** Stable, monotonic generator id for change tracking. */
  generatorVersion?: string;
  /** Provenance: which source artifact versions fed the report. */
  sourceArtifacts?: { kind: VentureArtifactKind; version: number }[];
  /** Override clock (tests). */
  now?: () => Date;
}

export interface RenderEvaluationReportOutput {
  artifact: EvaluationReport;
  /** Single-file Markdown render destined for EVALUATION_REPORT.md. */
  markdown: string;
}

export function renderEvaluationReport(input: RenderEvaluationReportInput): RenderEvaluationReportOutput {
  const generatedAt = (input.now ?? (() => new Date()))().toISOString();
  const generatorVersion = input.generatorVersion ?? 'evaluation-report@1';

  const personaCount = input.personas?.length ?? 0;
  const personaCoverage = {
    score: clamp01(personaCount === 0 ? 0 : Math.min(1, personaCount / 5)),
    count: personaCount,
    notes: personaNotes(input.personas),
  };

  const nodeCount = input.graph?.stats?.nodes ?? 0;
  const godNodeCount = input.graph?.godNodes?.length ?? 0;
  const contradictionCount = input.graph?.contradictions?.length ?? 0;
  const researchCoverage = {
    score: clamp01(nodeCount === 0 ? 0 : Math.min(1, nodeCount / 40)),
    nodeCount,
    godNodeCount,
    contradictionCount,
    topGodNodes: (input.graph?.godNodes ?? []).slice(0, 5).map((n) => ({
      label: n.label,
      weight: n.degree,
    })),
    notes: researchNotes(input.graph),
  };

  const risks = collectRisks(input.recommendation, input.committee, input.graph);
  const contradictionsPairs: { left: string; right: string }[] = (input.graph?.contradictions ?? []).map((c) => {
    const [left, right] = c.split('↔').map((s) => s.trim());
    return { left: left ?? c, right: right ?? '' };
  });
  const riskCoverage = {
    score: clamp01(risks.length === 0 ? 0 : Math.min(1, risks.length / 5)),
    identifiedRisks: risks,
    contradictions: contradictionsPairs,
    notes: riskNotes(risks, contradictionsPairs),
  };

  const rec = input.recommendation;
  const assumptions = (rec?.assumptions ?? []).map((a) => a.text);
  const openQuestions = (rec?.nextSteps ?? [])
    .filter((s) => s.blocksDecision)
    .map((s) => s.title);
  const validationRoadmap = {
    nextSteps: (rec?.nextSteps ?? []).slice(0, 8).map((s) => ({
      label: s.title,
      ...(s.category ? { owner: s.category } : {}),
    })),
    successCriteria: deriveSuccessCriteria(input.pack),
    killCriteria: deriveKillCriteria(rec),
  };

  const artifact: EvaluationReport = {
    kind: 'EvaluationReport',
    reportId: `er_${input.venture.ventureId}_${generatedAt.replace(/[^0-9]/g, '').slice(0, 14)}`,
    ventureId: input.venture.ventureId,
    generatedAt,
    generatorVersion,
    venture: {
      id: input.venture.ventureId,
      title: input.venture.title,
      status: input.venture.status,
      ...(input.venture.region ? { region: input.venture.region } : {}),
      ...(input.venture.customerType ? { customerType: input.venture.customerType } : {}),
    },
    readinessScore: input.readiness,
    recommendation: {
      decision: rec?.decision ?? null,
      confidence: rec?.confidenceScore ?? null,
      rationale: rec?.decisionRationale ?? [],
      ...(rec?.decision === 'PIVOT' && input.pack?.pivot
        ? { pivotOptions: [input.pack.pivot.revisedMvpDirection] }
        : {}),
    },
    coverage: {
      persona: personaCoverage,
      research: researchCoverage,
      risk: riskCoverage,
    },
    assumptions,
    openQuestions,
    validationRoadmap,
    provenance: {
      sourceArtifacts: input.sourceArtifacts ?? [],
    },
  };

  return { artifact, markdown: renderEvaluationMarkdown(artifact) };
}

function renderEvaluationMarkdown(r: EvaluationReport): string {
  const out: string[] = [];
  out.push(`# Evaluation report — ${r.venture.title}`);
  out.push('');
  out.push(`> Generated ${r.generatedAt} · \`${r.generatorVersion}\``);
  out.push('');
  out.push('## Readiness score');
  out.push(`- **Overall:** ${r.readinessScore.overall} / 100`);
  out.push(`- Persona coverage: ${r.readinessScore.personaCoverage}`);
  out.push(`- Research coverage: ${r.readinessScore.researchCoverage}`);
  out.push(`- Validation confidence: ${r.readinessScore.validationConfidence}`);
  out.push(`- BuildSquad completeness: ${r.readinessScore.buildsquadCompleteness}`);
  out.push(`- Risk coverage: ${r.readinessScore.riskCoverage}`);
  if (r.readinessScore.warnings.length > 0) {
    out.push('', '**Warnings**');
    out.push(...bullets(r.readinessScore.warnings));
  }
  out.push('');
  out.push('## Recommendation');
  out.push(`- **Decision:** ${r.recommendation.decision ?? '_none yet_'}`);
  if (r.recommendation.confidence != null) {
    out.push(`- Confidence: ${(r.recommendation.confidence * 100).toFixed(0)}%`);
  }
  if (r.recommendation.rationale.length > 0) {
    out.push('', '### Rationale');
    out.push(...bullets(r.recommendation.rationale));
  }
  if (r.recommendation.pivotOptions && r.recommendation.pivotOptions.length > 0) {
    out.push('', '### Pivot direction');
    out.push(...bullets(r.recommendation.pivotOptions));
  }
  out.push('');
  out.push('## Coverage');
  out.push(`- Persona: ${(r.coverage.persona.score * 100).toFixed(0)}% (${r.coverage.persona.count} personas)`);
  out.push(...indentBullets(r.coverage.persona.notes));
  out.push(`- Research: ${(r.coverage.research.score * 100).toFixed(0)}% (${r.coverage.research.nodeCount} nodes, ${r.coverage.research.godNodeCount} god-nodes, ${r.coverage.research.contradictionCount} contradictions)`);
  if (r.coverage.research.topGodNodes.length > 0) {
    out.push('  - Top god-nodes:');
    for (const g of r.coverage.research.topGodNodes) out.push(`    - ${g.label} (weight ${g.weight})`);
  }
  out.push(...indentBullets(r.coverage.research.notes));
  out.push(`- Risk: ${(r.coverage.risk.score * 100).toFixed(0)}% (${r.coverage.risk.identifiedRisks.length} risks)`);
  for (const risk of r.coverage.risk.identifiedRisks) {
    out.push(`  - _${risk.severity}_ (${risk.source}) — ${risk.label}`);
  }
  if (r.coverage.risk.contradictions.length > 0) {
    out.push('  - Contradictions:');
    for (const c of r.coverage.risk.contradictions) out.push(`    - ${c.left}${c.right ? ` ↔ ${c.right}` : ''}`);
  }
  out.push('');
  if (r.assumptions.length > 0) {
    out.push('## Assumptions');
    out.push(...bullets(r.assumptions));
    out.push('');
  }
  if (r.openQuestions.length > 0) {
    out.push('## Open questions');
    out.push(...bullets(r.openQuestions));
    out.push('');
  }
  out.push('## Validation roadmap');
  out.push('### Next steps');
  if (r.validationRoadmap.nextSteps.length === 0) out.push('_None._');
  for (const s of r.validationRoadmap.nextSteps) {
    out.push(`- ${s.label}${s.owner ? ` _(${s.owner})_` : ''}`);
  }
  out.push('', '### Success criteria');
  out.push(...bullets(r.validationRoadmap.successCriteria));
  out.push('', '### Kill criteria');
  out.push(...bullets(r.validationRoadmap.killCriteria));
  out.push('');
  if (r.provenance.sourceArtifacts.length > 0) {
    out.push('## Provenance');
    for (const s of r.provenance.sourceArtifacts) out.push(`- ${s.kind} v${s.version}`);
    out.push('');
  }
  return out.join('\n');
}

// ──────────── helpers ────────────────────────────────────────────────────

function bullets(items: string[] | undefined): string[] {
  if (!items || items.length === 0) return ['_None._'];
  return items.map((i) => `- ${i}`);
}

function indentBullets(items: string[]): string[] {
  return items.map((i) => `  - ${i}`);
}

function escTitle(s: string): string {
  return s.replace(/[\r\n]+/g, ' ').slice(0, 120);
}

function clamp01(x: number): number {
  if (!Number.isFinite(x)) return 0;
  return Math.max(0, Math.min(1, x));
}

function personaNotes(personas: PersonaLabPersona[] | null): string[] {
  if (!personas || personas.length === 0) return ['No persona set attached.'];
  const notes: string[] = [];
  notes.push(`${personas.length} persona${personas.length === 1 ? '' : 's'} on file.`);
  return notes;
}

function researchNotes(graph: ResearchGraph | null): string[] {
  if (!graph) return ['No research graph attached.'];
  const notes: string[] = [];
  if ((graph.stats?.nodes ?? 0) < 10) notes.push('Graph is sparse (<10 nodes).');
  if ((graph.contradictions?.length ?? 0) > 0) notes.push('Contradictions detected — review before proceeding.');
  return notes;
}

function riskNotes(risks: EvaluationReportRiskItem[], contradictions: { left: string; right: string }[]): string[] {
  const notes: string[] = [];
  if (risks.length === 0) notes.push('No risks identified — check recommendation/committee coverage.');
  const highs = risks.filter((r) => r.severity === 'high').length;
  if (highs > 0) notes.push(`${highs} high-severity risk${highs === 1 ? '' : 's'}.`);
  if (contradictions.length > 0) notes.push(`${contradictions.length} contradiction${contradictions.length === 1 ? '' : 's'} unresolved.`);
  return notes;
}

function collectRisks(
  rec: VentureRecommendation | null,
  committee: BuyingCommitteeTranscript | null,
  graph: ResearchGraph | null,
): EvaluationReportRiskItem[] {
  const out: EvaluationReportRiskItem[] = [];
  if (rec) {
    for (const r of rec.risks) out.push({ label: r.risk, severity: mapSeverity(r), source: 'recommendation' });
  }
  if (committee) {
    const objections = (committee as unknown as { objections?: string[] }).objections ?? [];
    for (const o of objections.slice(0, 5)) out.push({ label: o, severity: 'med', source: 'committee' });
  }
  if (graph?.contradictions) {
    for (const c of graph.contradictions.slice(0, 3)) {
      out.push({ label: `Contradiction: ${c}`, severity: 'med', source: 'graph' });
    }
  }
  return out;
}

function mapSeverity(r: VentureRisk): EvaluationReportRiskItem['severity'] {
  const impact = r.impact === 'high' ? 2 : r.impact === 'medium' ? 1 : 0;
  const likelihood = r.likelihood === 'high' ? 2 : r.likelihood === 'medium' ? 1 : 0;
  const score = impact + likelihood;
  if (score >= 3) return 'high';
  if (score >= 2) return 'med';
  return 'low';
}

function deriveSuccessCriteria(pack: BuildSquadArtifactPack | null): string[] {
  if (!pack) return ['_No BuildSquad pack — define success metrics during planning._'];
  return pack.productVision.successMetrics.length > 0
    ? pack.productVision.successMetrics
    : ['_Pack present but no success metrics captured._'];
}

function deriveKillCriteria(rec: VentureRecommendation | null): string[] {
  if (!rec) return ['_No recommendation yet — define kill criteria during validation._'];
  if (rec.decision === 'KILL') return rec.decisionRationale.slice(0, 5);
  return rec.nextSteps
    .filter((s) => s.blocksDecision)
    .slice(0, 5)
    .map((s) => `Kill if blocked by: ${s.title}`);
}
